import type { Metadata } from "next";
import "@/styles/global.css";
import { Toaster } from "sonner";

import { RouteTransitionOverlay } from "@/components/Overlays/Loading/RouteTransition";
import { ViewportHeightWatcher } from "@/components/Fanctional/ViewportHeightWatcher";
import { AuthSessionProvider } from "@/features/auth/components/AuthSessionProvider";
import { RedirectToastProvider } from "@/lib/redirectToast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />

      <body suppressHydrationWarning className="antialiased font-sans">
        <ViewportHeightWatcher />
        <AuthSessionProvider>
          <RouteTransitionOverlay />
          {children}
        </AuthSessionProvider>
        <Toaster position="bottom-center" richColors />
        <RedirectToastProvider />
      </body>
    </html>
  );
}
